ARG BASE_IMAGE=stevendargaville/petsc_64_bit

FROM ${BASE_IMAGE}
# Checkout the main branch by default
ARG BRANCH=main
# Use the optimised petsc build by default
ARG ARCH=arch-linux-c-opt

LABEL maintainer="Steven Dargaville"
LABEL description="BoxMeshDM_64_bit"

ENV CHECKOUT_BRANCH=$BRANCH
ENV PETSC_ARCH=$ARCH
# Ensure any test failures are caught and the build fails
ENV PETSC_OPTIONS="-on_error_abort"

WORKDIR /build

# Copy the source code and build it
COPY . /build/BoxMeshDM

RUN set -e; \
    cd BoxMeshDM && \
    make clean && make lib && \
    make clean && make && \
    make clean && make tests

WORKDIR /build/BoxMeshDM